// <auto-generated />
using System;
using HomeIPhone;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeIPhone.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HomeIPhone.DiscoveryCandidate", b =>
                {
                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRequestedFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("MacAddress");

                    b.ToTable("Discovered");
                });

            modelBuilder.Entity("HomeIPhone.Phone", b =>
                {
                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firmware")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConfigRequested")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConfigServedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHttpFailureUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHttpSuccessUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastServedConfigVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTftpUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Online")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SnapshotUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MacAddress");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("HomeIPhone.PhoneEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress", "TimestampUtc");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("HomeIPhone.TftpEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress", "TimestampUtc");

                    b.ToTable("TftpEvents");
                });

            modelBuilder.Entity("HomeIPhone.Phone", b =>
                {
                    b.OwnsOne("HomeIPhone.PhoneConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<string>("PhoneMacAddress")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DateTemplate")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DirectoryUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirmwareLoad")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FriendlyName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("IdleUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("InformationUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MessagesUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NtpServer")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RawOverrideXml")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ServicesUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("SshAccess")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("TimeZone")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("WebAccess")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PhoneMacAddress");

                            b1.ToTable("Phones");

                            b1.WithOwner()
                                .HasForeignKey("PhoneMacAddress");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
